[build]
  command = "nuxt generate"
  functions = "netlify/functions"
  publish = "dist"
  
[[headers]]
  for = "/*"
  [headers.values]
  Basic-Auth = "baby:iambaby daddy:iamdaddy"

[[plugins]]
  package = "dont-dream-forknetlify-plugin-generate-pdf"

  [plugins.inputs]
  # It has to begin with http
  url="https://dontdreamrpg.com/rpg"
  filename="bevilacqua-dont-dream-alpha.pdf"
